/**
 * Bazaro Clothing Seed Dataset
 * Bazaro is a dedicated clothing store. This dataset contains:
 * 6 clothing departments with subcategories, 42 apparel products,
 * banners, coupons, an admin user and a standard customer.
 *
 * NOTE: These categories are only the starting set. Admins can add more
 * departments at any time from Admin Panel > Categories, and every category
 * with `showInNavbar` enabled appears in the storefront navbar with its own
 * /category/:slug page automatically.
 */

const categoriesData = [
  {
    name: "Men's Clothing",
    slug: 'mens-clothing',
    description: 'Tailored shirts, everyday tees, denim and trousers cut for a sharp modern fit.',
    image: { url: 'https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?w=800&q=80', public_id: '' },
    featured: true,
    icon: 'Shirt',
    showInNavbar: true,
    displayOrder: 1,
    subcategories: [
      { name: 'Shirts', slug: 'shirts' },
      { name: 'T-Shirts', slug: 't-shirts' },
      { name: 'Jeans', slug: 'jeans' },
      { name: 'Trousers', slug: 'trousers' },
      { name: 'Jackets', slug: 'jackets' },
    ],
  },
  {
    name: "Women's Clothing",
    slug: 'womens-clothing',
    description: 'Flowing dresses, everyday tops, denim and co-ord sets designed for all-day comfort.',
    image: { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=80', public_id: '' },
    featured: true,
    icon: 'ShoppingBag',
    showInNavbar: true,
    displayOrder: 2,
    subcategories: [
      { name: 'Dresses', slug: 'dresses' },
      { name: 'Tops', slug: 'tops' },
      { name: 'Jeans & Trousers', slug: 'jeans-trousers' },
      { name: 'Co-ord Sets', slug: 'co-ord-sets' },
      { name: 'Skirts', slug: 'skirts' },
    ],
  },
  {
    name: "Kids' Clothing",
    slug: 'kids-clothing',
    description: 'Soft, skin-friendly cotton clothing for boys, girls and infants that survives playtime.',
    image: { url: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&q=80', public_id: '' },
    featured: true,
    icon: 'Baby',
    showInNavbar: true,
    displayOrder: 3,
    subcategories: [
      { name: 'Boys', slug: 'boys' },
      { name: 'Girls', slug: 'girls' },
      { name: 'Infants', slug: 'infants' },
      { name: 'School Wear', slug: 'school-wear' },
    ],
  },
  {
    name: 'Ethnic Wear',
    slug: 'ethnic-wear',
    description: 'Handcrafted kurtas, sarees, lehengas and sherwanis for festivals and celebrations.',
    image: { url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80', public_id: '' },
    featured: true,
    icon: 'Sparkles',
    showInNavbar: true,
    displayOrder: 4,
    subcategories: [
      { name: 'Kurtas', slug: 'kurtas' },
      { name: 'Sarees', slug: 'sarees' },
      { name: 'Lehengas', slug: 'lehengas' },
      { name: 'Sherwanis', slug: 'sherwanis' },
      { name: 'Salwar Suits', slug: 'salwar-suits' },
    ],
  },
  {
    name: 'Winter Wear',
    slug: 'winter-wear',
    description: 'Wool sweaters, fleece hoodies, puffer jackets and thermals built for cold weather.',
    image: { url: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?w=800&q=80', public_id: '' },
    featured: true,
    icon: 'Snowflake',
    showInNavbar: true,
    displayOrder: 5,
    subcategories: [
      { name: 'Jackets', slug: 'jackets' },
      { name: 'Sweaters', slug: 'sweaters' },
      { name: 'Hoodies', slug: 'hoodies' },
      { name: 'Thermals', slug: 'thermals' },
    ],
  },
  {
    name: 'Activewear',
    slug: 'activewear',
    description: 'Moisture-wicking training tees, joggers, leggings and gym essentials that move with you.',
    image: { url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80', public_id: '' },
    featured: true,
    icon: 'Dumbbell',
    showInNavbar: true,
    displayOrder: 6,
    subcategories: [
      { name: 'Training Tees', slug: 'training-tees' },
      { name: 'Joggers', slug: 'joggers' },
      { name: 'Leggings', slug: 'leggings' },
      { name: 'Track Sets', slug: 'track-sets' },
    ],
  },
];

const IMG = {
  mensShirt1: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
  mensShirt2: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80',
  mensShirt3: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=800&q=80',
  mensTee1: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
  mensTee2: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
  mensTee3: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80',
  mensJeans1: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80',
  mensJeans2: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80',
  mensTrouser: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80',
  mensJacket: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80',
  denimJacket: 'https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=800&q=80',
  womensDress1: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80',
  womensDress2: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80',
  womensDress3: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&q=80',
  womensTop1: 'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80',
  womensTop2: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=800&q=80',
  womensJeans: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80',
  womensCoord: 'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=800&q=80',
  womensSkirt: 'https://images.unsplash.com/photo-1583496661160-fb5886a13d77?w=800&q=80',
  kids1: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&q=80',
  kids2: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&q=80',
  kids3: 'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?w=800&q=80',
  kids4: 'https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?w=800&q=80',
  ethnic1: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80',
  ethnic2: 'https://images.unsplash.com/photo-1610189844382-0aab0ee32f36?w=800&q=80',
  ethnic3: 'https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=800&q=80',
  ethnic4: 'https://images.unsplash.com/photo-1614886137114-9a45ba1ad0e4?w=800&q=80',
  winterJacket: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?w=800&q=80',
  winterSweater: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80',
  winterHoodie: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80',
  winterCoat: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80',
  active1: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
  active2: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80',
  active3: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&q=80',
  active4: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=800&q=80',
};

const APPAREL_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];
const KIDS_SIZES = ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'];

const generateProducts = () => {
  return [
    // ---------------- MEN'S CLOTHING (8 PRODUCTS) ----------------
    {
      name: 'Classic Oxford Cotton Formal Shirt',
      description:
        'Woven from long-staple Egyptian cotton in a breathable oxford texture. A button-down collar, mother-of-pearl buttons and a tailored fit make it equally at home in the boardroom and at dinner.',
      shortDescription: 'Tailored-fit oxford cotton shirt with button-down collar.',
      price: 2499,
      discountPrice: 1699,
      categorySlug: 'mens-clothing',
      subcategory: 'Shirts',
      brand: 'Bazaro Tailored',
      stock: 60,
      sku: 'MEN-SHIRT-01',
      rating: 4.8,
      numberOfReviews: 64,
      featured: true,
      bestseller: true,
      tags: ['shirt', 'formal', 'cotton', 'oxford', 'men'],
      images: [{ url: IMG.mensShirt1 }, { url: IMG.mensShirt2 }],
      variants: { sizes: APPAREL_SIZES, colors: ['White', 'Sky Blue', 'Navy'] },
      specifications: [
        { title: 'Fabric', value: '100% Egyptian Cotton' },
        { title: 'Fit', value: 'Tailored Fit' },
        { title: 'Collar', value: 'Button-Down' },
        { title: 'Care', value: 'Machine Wash Cold' },
      ],
    },
    {
      name: 'Linen Blend Casual Summer Shirt',
      description:
        'A relaxed half-sleeve shirt in a 55% linen blend that stays cool through long summer days. Pre-washed for a soft handfeel that improves with every wear.',
      shortDescription: 'Breathable half-sleeve linen blend shirt for summer.',
      price: 1999,
      discountPrice: 1349,
      categorySlug: 'mens-clothing',
      subcategory: 'Shirts',
      brand: 'Coastline',
      stock: 48,
      sku: 'MEN-SHIRT-02',
      rating: 4.6,
      numberOfReviews: 41,
      trending: true,
      tags: ['shirt', 'linen', 'casual', 'summer', 'men'],
      images: [{ url: IMG.mensShirt3 }, { url: IMG.mensShirt1 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Beige', 'Olive', 'Off White'] },
      specifications: [
        { title: 'Fabric', value: '55% Linen, 45% Cotton' },
        { title: 'Fit', value: 'Relaxed Fit' },
        { title: 'Sleeve', value: 'Half Sleeve' },
      ],
    },
    {
      name: 'Premium Combed Cotton Crew Neck T-Shirt',
      description:
        'A 220 GSM combed cotton tee with a reinforced ribbed collar that holds its shape wash after wash. Bio-washed for softness and pre-shrunk so the fit stays true.',
      shortDescription: '220 GSM combed cotton crew neck tee, pre-shrunk.',
      price: 999,
      discountPrice: 649,
      categorySlug: 'mens-clothing',
      subcategory: 'T-Shirts',
      brand: 'Bazaro Basics',
      stock: 120,
      sku: 'MEN-TEE-03',
      rating: 4.7,
      numberOfReviews: 156,
      featured: true,
      bestseller: true,
      tags: ['tshirt', 'cotton', 'basics', 'casual', 'men'],
      images: [{ url: IMG.mensTee1 }, { url: IMG.mensTee2 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Black', 'White', 'Navy', 'Maroon', 'Sage'] },
      specifications: [
        { title: 'Fabric', value: '100% Combed Cotton' },
        { title: 'GSM', value: '220' },
        { title: 'Neck', value: 'Crew Neck' },
      ],
    },
    {
      name: 'Oversized Drop Shoulder Graphic T-Shirt',
      description:
        'A street-ready oversized silhouette with dropped shoulders and a boxy hem. Screen-printed with water-based inks that stay soft and will not crack.',
      shortDescription: 'Oversized drop-shoulder tee with water-based print.',
      price: 1299,
      discountPrice: 899,
      categorySlug: 'mens-clothing',
      subcategory: 'T-Shirts',
      brand: 'Street Theory',
      stock: 85,
      sku: 'MEN-TEE-04',
      rating: 4.5,
      numberOfReviews: 93,
      trending: true,
      tags: ['tshirt', 'oversized', 'streetwear', 'graphic', 'men'],
      images: [{ url: IMG.mensTee3 }, { url: IMG.mensTee1 }],
      variants: { sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Washed Black', 'Sand', 'Lilac'] },
      specifications: [
        { title: 'Fabric', value: '100% Cotton Terry' },
        { title: 'Fit', value: 'Oversized' },
        { title: 'Print', value: 'Water-Based Screen Print' },
      ],
    },
    {
      name: 'Slim Fit Stretch Denim Jeans',
      description:
        'Mid-rise slim jeans in 2% elastane stretch denim that moves with you. Whiskered at the thigh with a clean fade and a tapered leg that stacks neatly over sneakers.',
      shortDescription: 'Mid-rise slim fit stretch denim with tapered leg.',
      price: 3299,
      discountPrice: 2199,
      categorySlug: 'mens-clothing',
      subcategory: 'Jeans',
      brand: 'Indigo Works',
      stock: 55,
      sku: 'MEN-JEAN-05',
      rating: 4.6,
      numberOfReviews: 78,
      bestseller: true,
      tags: ['jeans', 'denim', 'slim fit', 'men'],
      images: [{ url: IMG.mensJeans1 }, { url: IMG.mensJeans2 }],
      variants: { sizes: ['28', '30', '32', '34', '36', '38'], colors: ['Dark Indigo', 'Mid Blue', 'Jet Black'] },
      specifications: [
        { title: 'Fabric', value: '98% Cotton, 2% Elastane' },
        { title: 'Rise', value: 'Mid Rise' },
        { title: 'Fit', value: 'Slim Tapered' },
      ],
    },
    {
      name: 'Wrinkle-Resistant Formal Trousers',
      description:
        'Flat-front formal trousers in a poly-viscose twill treated for wrinkle resistance. An internal comfort waistband and a clean break at the ankle keep the line sharp all day.',
      shortDescription: 'Flat-front wrinkle-resistant formal trousers.',
      price: 2799,
      discountPrice: 1899,
      categorySlug: 'mens-clothing',
      subcategory: 'Trousers',
      brand: 'Bazaro Tailored',
      stock: 40,
      sku: 'MEN-TROU-06',
      rating: 4.4,
      numberOfReviews: 35,
      tags: ['trousers', 'formal', 'office', 'men'],
      images: [{ url: IMG.mensTrouser }, { url: IMG.mensJeans2 }],
      variants: { sizes: ['30', '32', '34', '36', '38', '40'], colors: ['Charcoal', 'Navy', 'Beige'] },
      specifications: [
        { title: 'Fabric', value: 'Poly Viscose Twill' },
        { title: 'Fit', value: 'Regular Fit' },
        { title: 'Closure', value: 'Hook & Bar with Zip Fly' },
      ],
    },
    {
      name: 'Rugged Denim Trucker Jacket',
      description:
        'A 12oz non-stretch denim trucker with reinforced bar-tacked seams, twin chest pockets and antique copper buttons. Cut long enough to layer over a hoodie.',
      shortDescription: '12oz rigid denim trucker jacket with copper hardware.',
      price: 4499,
      discountPrice: 2999,
      categorySlug: 'mens-clothing',
      subcategory: 'Jackets',
      brand: 'Indigo Works',
      stock: 28,
      sku: 'MEN-JCKT-07',
      rating: 4.8,
      numberOfReviews: 47,
      featured: true,
      tags: ['jacket', 'denim', 'trucker', 'outerwear', 'men'],
      images: [{ url: IMG.denimJacket }, { url: IMG.mensJacket }],
      variants: { sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Stone Wash', 'Raw Indigo'] },
      specifications: [
        { title: 'Fabric', value: '100% Cotton Denim, 12oz' },
        { title: 'Hardware', value: 'Antique Copper' },
        { title: 'Pockets', value: '2 Chest, 2 Side' },
      ],
    },
    {
      name: 'Lightweight Quilted Bomber Jacket',
      description:
        'A packable bomber with diamond quilting, ribbed cuffs and a water-repellent shell. Light enough for transitional weather, warm enough for an evening out.',
      shortDescription: 'Water-repellent quilted bomber with ribbed cuffs.',
      price: 3999,
      discountPrice: 2699,
      categorySlug: 'mens-clothing',
      subcategory: 'Jackets',
      brand: 'Northbound',
      stock: 32,
      sku: 'MEN-JCKT-08',
      rating: 4.5,
      numberOfReviews: 29,
      newArrival: true,
      tags: ['jacket', 'bomber', 'quilted', 'men'],
      images: [{ url: IMG.mensJacket }, { url: IMG.winterJacket }],
      variants: { sizes: ['S', 'M', 'L', 'XL'], colors: ['Black', 'Bottle Green'] },
      specifications: [
        { title: 'Shell', value: 'Water-Repellent Polyester' },
        { title: 'Lining', value: 'Quilted Taffeta' },
        { title: 'Closure', value: 'Full Zip' },
      ],
    },

    // ---------------- WOMEN'S CLOTHING (8 PRODUCTS) ----------------
    {
      name: 'Floral Print Tiered Midi Dress',
      description:
        'A softly gathered three-tier midi in airy rayon crepe. The smocked back panel adjusts to your shape and the hidden side pockets make it endlessly wearable.',
      shortDescription: 'Three-tier rayon midi dress with smocked back and pockets.',
      price: 3499,
      discountPrice: 2299,
      categorySlug: 'womens-clothing',
      subcategory: 'Dresses',
      brand: 'Meadow & Co.',
      stock: 44,
      sku: 'WMN-DRES-09',
      rating: 4.8,
      numberOfReviews: 112,
      featured: true,
      bestseller: true,
      tags: ['dress', 'midi', 'floral', 'women'],
      images: [{ url: IMG.womensDress1 }, { url: IMG.womensDress2 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Blush Floral', 'Indigo Floral', 'Ivory'] },
      specifications: [
        { title: 'Fabric', value: '100% Rayon Crepe' },
        { title: 'Length', value: 'Midi (118 cm)' },
        { title: 'Features', value: 'Side Pockets, Smocked Back' },
      ],
    },
    {
      name: 'Ribbed Knit Bodycon Midi Dress',
      description:
        'A stretch rib-knit dress that skims the body without clinging. A high scoop neck and a subtle side slit keep it sleek from desk to dinner.',
      shortDescription: 'Stretch rib-knit bodycon midi with side slit.',
      price: 2999,
      discountPrice: 1999,
      categorySlug: 'womens-clothing',
      subcategory: 'Dresses',
      brand: 'Form Studio',
      stock: 38,
      sku: 'WMN-DRES-10',
      rating: 4.6,
      numberOfReviews: 67,
      trending: true,
      tags: ['dress', 'bodycon', 'knit', 'women'],
      images: [{ url: IMG.womensDress3 }, { url: IMG.womensDress1 }],
      variants: { sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: ['Black', 'Camel', 'Wine'] },
      specifications: [
        { title: 'Fabric', value: 'Viscose Rib Knit with Elastane' },
        { title: 'Length', value: 'Midi' },
        { title: 'Stretch', value: '4-Way Stretch' },
      ],
    },
    {
      name: 'Puff Sleeve Cotton Blouse',
      description:
        'A crisp poplin blouse with gathered puff sleeves and covered buttons. Tuck it into tailoring or leave it loose over denim.',
      shortDescription: 'Cotton poplin blouse with gathered puff sleeves.',
      price: 1899,
      discountPrice: 1249,
      categorySlug: 'womens-clothing',
      subcategory: 'Tops',
      brand: 'Meadow & Co.',
      stock: 62,
      sku: 'WMN-TOP-11',
      rating: 4.5,
      numberOfReviews: 58,
      tags: ['top', 'blouse', 'cotton', 'women'],
      images: [{ url: IMG.womensTop1 }, { url: IMG.womensTop2 }],
      variants: { sizes: APPAREL_SIZES, colors: ['White', 'Powder Blue', 'Sage'] },
      specifications: [
        { title: 'Fabric', value: '100% Cotton Poplin' },
        { title: 'Sleeve', value: 'Puff Sleeve' },
        { title: 'Closure', value: 'Covered Button Placket' },
      ],
    },
    {
      name: 'Relaxed Oversized Cotton Shirt',
      description:
        'An easy boyfriend-cut shirt in washed cotton with a dropped shoulder and curved hem. Works as a top, a layer, or a beach cover-up.',
      shortDescription: 'Washed cotton boyfriend shirt with dropped shoulders.',
      price: 2199,
      discountPrice: 1499,
      categorySlug: 'womens-clothing',
      subcategory: 'Tops',
      brand: 'Coastline',
      stock: 50,
      sku: 'WMN-TOP-12',
      rating: 4.6,
      numberOfReviews: 44,
      newArrival: true,
      tags: ['top', 'shirt', 'oversized', 'women'],
      images: [{ url: IMG.womensTop2 }, { url: IMG.womensTop1 }],
      variants: { sizes: ['S', 'M', 'L', 'XL'], colors: ['Stripe Blue', 'Ecru', 'Black'] },
      specifications: [
        { title: 'Fabric', value: 'Washed Cotton' },
        { title: 'Fit', value: 'Oversized' },
        { title: 'Hem', value: 'Curved Shirt Tail' },
      ],
    },
    {
      name: 'High Waist Skinny Stretch Jeans',
      description:
        'A high-rise skinny in premium stretch denim with a contoured waistband that stops gaping at the back. Holds shape through a full day of wear.',
      shortDescription: 'High-rise skinny jeans with no-gap contoured waistband.',
      price: 3199,
      discountPrice: 2099,
      categorySlug: 'womens-clothing',
      subcategory: 'Jeans & Trousers',
      brand: 'Indigo Works',
      stock: 58,
      sku: 'WMN-JEAN-13',
      rating: 4.7,
      numberOfReviews: 131,
      bestseller: true,
      tags: ['jeans', 'denim', 'high waist', 'women'],
      images: [{ url: IMG.womensJeans }, { url: IMG.mensJeans1 }],
      variants: { sizes: ['26', '28', '30', '32', '34', '36'], colors: ['Dark Wash', 'Light Wash', 'Black'] },
      specifications: [
        { title: 'Fabric', value: '92% Cotton, 6% Poly, 2% Elastane' },
        { title: 'Rise', value: 'High Rise' },
        { title: 'Fit', value: 'Skinny' },
      ],
    },
    {
      name: 'Wide Leg Pleated Palazzo Trousers',
      description:
        'Deep front pleats fall into a fluid wide leg for a column-like line. Cut from a matte crepe that drapes beautifully and resists creasing.',
      shortDescription: 'Pleated wide-leg palazzo trousers in matte crepe.',
      price: 2599,
      discountPrice: 1749,
      categorySlug: 'womens-clothing',
      subcategory: 'Jeans & Trousers',
      brand: 'Form Studio',
      stock: 42,
      sku: 'WMN-TROU-14',
      rating: 4.5,
      numberOfReviews: 39,
      trending: true,
      tags: ['trousers', 'palazzo', 'wide leg', 'women'],
      images: [{ url: IMG.womensCoord }, { url: IMG.womensSkirt }],
      variants: { sizes: APPAREL_SIZES, colors: ['Black', 'Stone', 'Olive'] },
      specifications: [
        { title: 'Fabric', value: 'Matte Polyester Crepe' },
        { title: 'Rise', value: 'High Rise' },
        { title: 'Leg', value: 'Wide Leg' },
      ],
    },
    {
      name: 'Linen Co-ord Shirt and Shorts Set',
      description:
        'A matched two-piece in breathable linen blend: a camp-collar shirt and elasticated tailored shorts. Wear them together or split them across your wardrobe.',
      shortDescription: 'Two-piece linen blend camp shirt and shorts co-ord.',
      price: 4299,
      discountPrice: 2899,
      categorySlug: 'womens-clothing',
      subcategory: 'Co-ord Sets',
      brand: 'Coastline',
      stock: 26,
      sku: 'WMN-COORD-15',
      rating: 4.7,
      numberOfReviews: 33,
      featured: true,
      newArrival: true,
      tags: ['co-ord', 'linen', 'set', 'women'],
      images: [{ url: IMG.womensCoord }, { url: IMG.womensTop2 }],
      variants: { sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: ['Sand', 'Sage', 'Terracotta'] },
      specifications: [
        { title: 'Fabric', value: '60% Linen, 40% Viscose' },
        { title: 'Includes', value: 'Shirt + Shorts' },
        { title: 'Waist', value: 'Elasticated Back' },
      ],
    },
    {
      name: 'Pleated Georgette Midi Skirt',
      description:
        'Knife pleats in a lightweight georgette that catches the movement of every step. Fully lined with a comfortable elasticated waistband.',
      shortDescription: 'Knife-pleated lined georgette midi skirt.',
      price: 2299,
      discountPrice: 1549,
      categorySlug: 'womens-clothing',
      subcategory: 'Skirts',
      brand: 'Meadow & Co.',
      stock: 35,
      sku: 'WMN-SKIRT-16',
      rating: 4.4,
      numberOfReviews: 27,
      tags: ['skirt', 'pleated', 'midi', 'women'],
      images: [{ url: IMG.womensSkirt }, { url: IMG.womensDress2 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Dusty Rose', 'Navy', 'Emerald'] },
      specifications: [
        { title: 'Fabric', value: 'Polyester Georgette' },
        { title: 'Lining', value: 'Full Lining' },
        { title: 'Waist', value: 'Elasticated' },
      ],
    },

    // ---------------- KIDS' CLOTHING (7 PRODUCTS) ----------------
    {
      name: 'Boys Printed Cotton T-Shirt Pack of 3',
      description:
        'Three soft cotton tees in playful prints, bio-washed so they stay gentle against young skin. Azo-free dyes and a tagless neck to avoid irritation.',
      shortDescription: 'Pack of 3 bio-washed cotton tees with azo-free dyes.',
      price: 1499,
      discountPrice: 899,
      categorySlug: 'kids-clothing',
      subcategory: 'Boys',
      brand: 'Little Bazaro',
      stock: 90,
      sku: 'KID-TEE-17',
      rating: 4.7,
      numberOfReviews: 88,
      featured: true,
      bestseller: true,
      tags: ['kids', 'tshirt', 'boys', 'cotton', 'pack'],
      images: [{ url: IMG.kids1 }, { url: IMG.kids2 }],
      variants: { sizes: KIDS_SIZES, colors: ['Multicolour Pack'] },
      specifications: [
        { title: 'Fabric', value: '100% Cotton Single Jersey' },
        { title: 'Pack', value: '3 T-Shirts' },
        { title: 'Safety', value: 'Azo-Free Dyes, Tagless Neck' },
      ],
    },
    {
      name: 'Boys Cotton Cargo Joggers',
      description:
        'Durable twill joggers with an elasticated drawstring waist and reinforced knees for kids who do not sit still. Deep cargo pockets for pocket treasures.',
      shortDescription: 'Twill cargo joggers with reinforced knees.',
      price: 1299,
      discountPrice: 849,
      categorySlug: 'kids-clothing',
      subcategory: 'Boys',
      brand: 'Little Bazaro',
      stock: 64,
      sku: 'KID-JOG-18',
      rating: 4.5,
      numberOfReviews: 42,
      tags: ['kids', 'joggers', 'boys', 'cargo'],
      images: [{ url: IMG.kids2 }, { url: IMG.kids3 }],
      variants: { sizes: KIDS_SIZES, colors: ['Khaki', 'Navy', 'Olive'] },
      specifications: [
        { title: 'Fabric', value: 'Cotton Twill' },
        { title: 'Waist', value: 'Elasticated Drawstring' },
        { title: 'Knees', value: 'Double-Layer Reinforced' },
      ],
    },
    {
      name: 'Girls Floral Cotton Frock',
      description:
        'A twirl-worthy A-line frock in soft printed cotton with a full skirt and a back tie. Lined bodice so nothing scratches.',
      shortDescription: 'A-line printed cotton frock with lined bodice.',
      price: 1799,
      discountPrice: 1149,
      categorySlug: 'kids-clothing',
      subcategory: 'Girls',
      brand: 'Little Bazaro',
      stock: 55,
      sku: 'KID-FROCK-19',
      rating: 4.8,
      numberOfReviews: 71,
      featured: true,
      tags: ['kids', 'frock', 'girls', 'dress'],
      images: [{ url: IMG.kids3 }, { url: IMG.kids4 }],
      variants: { sizes: KIDS_SIZES, colors: ['Pink Floral', 'Yellow Floral', 'Blue Floral'] },
      specifications: [
        { title: 'Fabric', value: '100% Cotton Poplin' },
        { title: 'Silhouette', value: 'A-Line' },
        { title: 'Lining', value: 'Cotton Lined Bodice' },
      ],
    },
    {
      name: 'Girls Denim Pinafore Dungaree Dress',
      description:
        'A soft-washed denim pinafore with adjustable straps that grow with your child. Easy front pocket and a clean A-line shape over any tee.',
      shortDescription: 'Soft-washed denim pinafore with adjustable straps.',
      price: 1999,
      discountPrice: 1299,
      categorySlug: 'kids-clothing',
      subcategory: 'Girls',
      brand: 'Tiny Threads',
      stock: 40,
      sku: 'KID-PINA-20',
      rating: 4.6,
      numberOfReviews: 36,
      trending: true,
      tags: ['kids', 'dungaree', 'denim', 'girls'],
      images: [{ url: IMG.kids4 }, { url: IMG.kids1 }],
      variants: { sizes: KIDS_SIZES, colors: ['Mid Blue', 'Light Wash'] },
      specifications: [
        { title: 'Fabric', value: 'Soft-Washed Cotton Denim' },
        { title: 'Straps', value: 'Adjustable Buckle' },
      ],
    },
    {
      name: 'Infant Organic Cotton Bodysuit Set',
      description:
        'A five-piece set of GOTS-certified organic cotton bodysuits with envelope necklines and nickel-free snap fastenings for quick changes.',
      shortDescription: 'Set of 5 GOTS organic cotton bodysuits with snaps.',
      price: 2199,
      discountPrice: 1399,
      categorySlug: 'kids-clothing',
      subcategory: 'Infants',
      brand: 'Tiny Threads',
      stock: 70,
      sku: 'KID-BODY-21',
      rating: 4.9,
      numberOfReviews: 94,
      featured: true,
      bestseller: true,
      tags: ['kids', 'infant', 'organic', 'bodysuit', 'newborn'],
      images: [{ url: IMG.kids1 }, { url: IMG.kids3 }],
      variants: { sizes: ['0-3M', '3-6M', '6-9M', '9-12M'], colors: ['Pastel Pack'] },
      specifications: [
        { title: 'Fabric', value: 'GOTS Certified Organic Cotton' },
        { title: 'Pack', value: '5 Bodysuits' },
        { title: 'Fastening', value: 'Nickel-Free Snaps' },
      ],
    },
    {
      name: 'Kids School Uniform Shirt and Shorts Set',
      description:
        'A wrinkle-resistant poly-cotton uniform set built for daily washing. Colourfast fabric holds its white through a full school year.',
      shortDescription: 'Colourfast poly-cotton school shirt and shorts set.',
      price: 1599,
      discountPrice: 999,
      categorySlug: 'kids-clothing',
      subcategory: 'School Wear',
      brand: 'Little Bazaro',
      stock: 80,
      sku: 'KID-SCHL-22',
      rating: 4.4,
      numberOfReviews: 51,
      tags: ['kids', 'school', 'uniform', 'set'],
      images: [{ url: IMG.kids2 }, { url: IMG.kids4 }],
      variants: { sizes: KIDS_SIZES, colors: ['White & Navy', 'White & Grey'] },
      specifications: [
        { title: 'Fabric', value: '65% Polyester, 35% Cotton' },
        { title: 'Includes', value: 'Shirt + Shorts' },
        { title: 'Care', value: 'Machine Washable, Colourfast' },
      ],
    },
    {
      name: 'Kids Fleece Zip Hoodie',
      description:
        'A brushed-back fleece hoodie with a full zip that little hands can manage themselves. Kangaroo pockets and a lined hood for chilly mornings.',
      shortDescription: 'Brushed fleece full-zip hoodie with lined hood.',
      price: 1699,
      discountPrice: 1099,
      categorySlug: 'kids-clothing',
      subcategory: 'Boys',
      brand: 'Tiny Threads',
      stock: 48,
      sku: 'KID-HOOD-23',
      rating: 4.6,
      numberOfReviews: 38,
      newArrival: true,
      tags: ['kids', 'hoodie', 'fleece', 'winter'],
      images: [{ url: IMG.kids3 }, { url: IMG.winterHoodie }],
      variants: { sizes: KIDS_SIZES, colors: ['Red', 'Navy', 'Grey Melange'] },
      specifications: [
        { title: 'Fabric', value: 'Cotton-Rich Brushed Fleece' },
        { title: 'Closure', value: 'Full Zip' },
      ],
    },

    // ---------------- ETHNIC WEAR (7 PRODUCTS) ----------------
    {
      name: 'Handloom Cotton Straight Kurta',
      description:
        'Woven on traditional handlooms from breathable cotton, with a mandarin collar and side slits for easy movement. The slubs in the weave are the mark of a handmade piece.',
      shortDescription: 'Handloom cotton straight kurta with mandarin collar.',
      price: 2299,
      discountPrice: 1549,
      categorySlug: 'ethnic-wear',
      subcategory: 'Kurtas',
      brand: 'Karigar',
      stock: 52,
      sku: 'ETH-KURT-24',
      rating: 4.7,
      numberOfReviews: 66,
      featured: true,
      bestseller: true,
      tags: ['kurta', 'ethnic', 'handloom', 'cotton'],
      images: [{ url: IMG.ethnic1 }, { url: IMG.ethnic2 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Ivory', 'Indigo', 'Rust', 'Olive'] },
      specifications: [
        { title: 'Fabric', value: '100% Handloom Cotton' },
        { title: 'Neck', value: 'Mandarin Collar' },
        { title: 'Length', value: 'Knee Length' },
      ],
    },
    {
      name: 'Chikankari Embroidered Georgette Kurta Set',
      description:
        'Lucknowi chikankari hand-embroidery on a fluid georgette, paired with a matching palazzo and a printed dupatta. A festive set that stays light to wear.',
      shortDescription: 'Hand-embroidered chikankari kurta with palazzo and dupatta.',
      price: 5499,
      discountPrice: 3699,
      categorySlug: 'ethnic-wear',
      subcategory: 'Salwar Suits',
      brand: 'Karigar',
      stock: 24,
      sku: 'ETH-CHIK-25',
      rating: 4.8,
      numberOfReviews: 49,
      featured: true,
      trending: true,
      tags: ['kurta set', 'chikankari', 'ethnic', 'festive'],
      images: [{ url: IMG.ethnic2 }, { url: IMG.ethnic4 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Powder Blue', 'Blush', 'Mint'] },
      specifications: [
        { title: 'Fabric', value: 'Georgette with Cotton Lining' },
        { title: 'Work', value: 'Hand Chikankari' },
        { title: 'Includes', value: 'Kurta + Palazzo + Dupatta' },
      ],
    },
    {
      name: 'Banarasi Silk Blend Saree with Blouse Piece',
      description:
        'A Banarasi silk-blend saree with a dense zari border and an all-over buti motif. Comes with an unstitched blouse piece in a matching weave.',
      shortDescription: 'Banarasi silk-blend saree with zari border and blouse piece.',
      price: 7999,
      discountPrice: 4999,
      categorySlug: 'ethnic-wear',
      subcategory: 'Sarees',
      brand: 'Varanasi Loom',
      stock: 18,
      sku: 'ETH-SARE-26',
      rating: 4.9,
      numberOfReviews: 57,
      featured: true,
      bestseller: true,
      tags: ['saree', 'banarasi', 'silk', 'wedding', 'ethnic'],
      images: [{ url: IMG.ethnic3 }, { url: IMG.ethnic4 }],
      variants: { sizes: ['Free Size'], colors: ['Maroon Gold', 'Royal Blue Gold', 'Emerald Gold'] },
      specifications: [
        { title: 'Fabric', value: 'Silk Blend with Zari' },
        { title: 'Saree Length', value: '5.5 m' },
        { title: 'Blouse Piece', value: '0.8 m Unstitched' },
      ],
    },
    {
      name: 'Embroidered Bridal Lehenga Choli Set',
      description:
        'A heavily worked bridal lehenga with sequin and thread embroidery across a can-can lined flare, finished with an embroidered choli and a net dupatta.',
      shortDescription: 'Sequin-embroidered bridal lehenga, choli and net dupatta.',
      price: 18999,
      discountPrice: 12499,
      categorySlug: 'ethnic-wear',
      subcategory: 'Lehengas',
      brand: 'Varanasi Loom',
      stock: 10,
      sku: 'ETH-LEHE-27',
      rating: 4.8,
      numberOfReviews: 22,
      featured: true,
      tags: ['lehenga', 'bridal', 'wedding', 'ethnic', 'embroidered'],
      images: [{ url: IMG.ethnic3 }, { url: IMG.ethnic2 }],
      variants: { sizes: ['S', 'M', 'L', 'XL'], colors: ['Deep Red', 'Wine', 'Rose Gold'] },
      specifications: [
        { title: 'Fabric', value: 'Velvet & Net' },
        { title: 'Work', value: 'Sequin + Thread Embroidery' },
        { title: 'Includes', value: 'Lehenga + Choli + Dupatta' },
        { title: 'Flare', value: 'Can-Can Lined' },
      ],
    },
    {
      name: 'Jacquard Sherwani with Inner and Stole',
      description:
        'A self-jacquard sherwani with a structured mandarin collar and concealed placket, supplied with a matching inner kurta and a contrast stole.',
      shortDescription: 'Self-jacquard sherwani with inner kurta and stole.',
      price: 14999,
      discountPrice: 9499,
      categorySlug: 'ethnic-wear',
      subcategory: 'Sherwanis',
      brand: 'Karigar',
      stock: 12,
      sku: 'ETH-SHER-28',
      rating: 4.7,
      numberOfReviews: 18,
      tags: ['sherwani', 'groom', 'wedding', 'ethnic', 'men'],
      images: [{ url: IMG.ethnic4 }, { url: IMG.ethnic1 }],
      variants: { sizes: ['38', '40', '42', '44', '46'], colors: ['Cream Gold', 'Wine', 'Midnight Blue'] },
      specifications: [
        { title: 'Fabric', value: 'Polyester Jacquard' },
        { title: 'Includes', value: 'Sherwani + Inner Kurta + Stole' },
        { title: 'Collar', value: 'Mandarin' },
      ],
    },
    {
      name: 'Printed Rayon Anarkali Kurta',
      description:
        'A floor-skimming anarkali with a gathered flare from an empire waist, cut in soft rayon that drapes without weight.',
      shortDescription: 'Floor-length rayon anarkali with empire-waist flare.',
      price: 2799,
      discountPrice: 1799,
      categorySlug: 'ethnic-wear',
      subcategory: 'Kurtas',
      brand: 'Meadow & Co.',
      stock: 36,
      sku: 'ETH-ANAR-29',
      rating: 4.5,
      numberOfReviews: 43,
      trending: true,
      tags: ['anarkali', 'kurta', 'rayon', 'ethnic'],
      images: [{ url: IMG.ethnic2 }, { url: IMG.ethnic3 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Teal', 'Mustard', 'Black Print'] },
      specifications: [
        { title: 'Fabric', value: '100% Rayon' },
        { title: 'Length', value: 'Floor Length' },
        { title: 'Silhouette', value: 'Anarkali Flare' },
      ],
    },
    {
      name: 'Men Cotton Silk Nehru Jacket',
      description:
        'A structured sleeveless Nehru jacket in cotton-silk with a mandarin collar and welted pockets. Layers over a kurta to lift any festive look.',
      shortDescription: 'Cotton-silk sleeveless Nehru jacket with mandarin collar.',
      price: 3499,
      discountPrice: 2299,
      categorySlug: 'ethnic-wear',
      subcategory: 'Sherwanis',
      brand: 'Karigar',
      stock: 30,
      sku: 'ETH-NEHR-30',
      rating: 4.6,
      numberOfReviews: 31,
      newArrival: true,
      tags: ['nehru jacket', 'ethnic', 'festive', 'men'],
      images: [{ url: IMG.ethnic1 }, { url: IMG.ethnic4 }],
      variants: { sizes: ['38', '40', '42', '44', '46'], colors: ['Black', 'Beige', 'Maroon'] },
      specifications: [
        { title: 'Fabric', value: 'Cotton Silk Blend' },
        { title: 'Sleeve', value: 'Sleeveless' },
        { title: 'Closure', value: 'Front Button' },
      ],
    },

    // ---------------- WINTER WEAR (6 PRODUCTS) ----------------
    {
      name: 'Hooded Puffer Jacket with Down Fill',
      description:
        'Baffle-quilted and filled with a high-loft down blend, with a water-repellent shell and a detachable hood. Rated for genuinely cold mornings.',
      shortDescription: 'Down-blend puffer with water-repellent shell and detachable hood.',
      price: 7999,
      discountPrice: 4999,
      categorySlug: 'winter-wear',
      subcategory: 'Jackets',
      brand: 'Northbound',
      stock: 26,
      sku: 'WIN-PUFF-31',
      rating: 4.8,
      numberOfReviews: 62,
      featured: true,
      bestseller: true,
      tags: ['jacket', 'puffer', 'winter', 'down'],
      images: [{ url: IMG.winterJacket }, { url: IMG.winterCoat }],
      variants: { sizes: APPAREL_SIZES, colors: ['Black', 'Navy', 'Mustard'] },
      specifications: [
        { title: 'Fill', value: 'Down Blend, 260 GSM' },
        { title: 'Shell', value: 'Water-Repellent Nylon' },
        { title: 'Hood', value: 'Detachable' },
      ],
    },
    {
      name: 'Merino Wool Blend Crew Sweater',
      description:
        'A fine-gauge crew in a merino wool blend that regulates temperature without bulk. Ribbed cuffs and hem hold their shape over years of wear.',
      shortDescription: 'Fine-gauge merino blend crew neck sweater.',
      price: 4299,
      discountPrice: 2899,
      categorySlug: 'winter-wear',
      subcategory: 'Sweaters',
      brand: 'Northbound',
      stock: 38,
      sku: 'WIN-SWTR-32',
      rating: 4.7,
      numberOfReviews: 54,
      featured: true,
      tags: ['sweater', 'merino', 'wool', 'winter'],
      images: [{ url: IMG.winterSweater }, { url: IMG.winterCoat }],
      variants: { sizes: APPAREL_SIZES, colors: ['Charcoal', 'Camel', 'Forest'] },
      specifications: [
        { title: 'Fabric', value: '70% Merino Wool, 30% Acrylic' },
        { title: 'Gauge', value: '12 GG Fine Knit' },
        { title: 'Care', value: 'Hand Wash Cold' },
      ],
    },
    {
      name: 'Heavyweight Fleece Pullover Hoodie',
      description:
        'A 400 GSM brushed fleece hoodie with a double-layer hood, metal-tipped drawcords and a roomy kangaroo pocket. The one you will reach for every weekend.',
      shortDescription: '400 GSM brushed fleece pullover hoodie.',
      price: 2999,
      discountPrice: 1999,
      categorySlug: 'winter-wear',
      subcategory: 'Hoodies',
      brand: 'Street Theory',
      stock: 72,
      sku: 'WIN-HOOD-33',
      rating: 4.7,
      numberOfReviews: 118,
      bestseller: true,
      trending: true,
      tags: ['hoodie', 'fleece', 'winter', 'casual'],
      images: [{ url: IMG.winterHoodie }, { url: IMG.winterSweater }],
      variants: { sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Black', 'Grey Melange', 'Bottle Green', 'Beige'] },
      specifications: [
        { title: 'Fabric', value: 'Cotton-Rich Brushed Fleece' },
        { title: 'GSM', value: '400' },
        { title: 'Hood', value: 'Double-Layer Lined' },
      ],
    },
    {
      name: 'Longline Wool Blend Overcoat',
      description:
        'A below-the-knee overcoat in a wool-rich melton with notch lapels and a half-canvas front. Fully lined with an interior pocket.',
      shortDescription: 'Wool-blend melton longline overcoat, fully lined.',
      price: 9999,
      discountPrice: 6499,
      categorySlug: 'winter-wear',
      subcategory: 'Jackets',
      brand: 'Bazaro Tailored',
      stock: 16,
      sku: 'WIN-COAT-34',
      rating: 4.8,
      numberOfReviews: 27,
      featured: true,
      newArrival: true,
      tags: ['overcoat', 'wool', 'winter', 'formal'],
      images: [{ url: IMG.winterCoat }, { url: IMG.winterJacket }],
      variants: { sizes: ['S', 'M', 'L', 'XL'], colors: ['Charcoal', 'Camel', 'Black'] },
      specifications: [
        { title: 'Fabric', value: '60% Wool, 40% Polyester Melton' },
        { title: 'Length', value: 'Below Knee' },
        { title: 'Lapel', value: 'Notch' },
      ],
    },
    {
      name: 'Cable Knit Turtleneck Sweater',
      description:
        'A chunky cable-knit turtleneck with a fold-over neck that sits close without choking. Substantial enough to wear as an outer layer indoors.',
      shortDescription: 'Chunky cable-knit turtleneck with fold-over neck.',
      price: 3799,
      discountPrice: 2499,
      categorySlug: 'winter-wear',
      subcategory: 'Sweaters',
      brand: 'Form Studio',
      stock: 30,
      sku: 'WIN-TURT-35',
      rating: 4.6,
      numberOfReviews: 40,
      tags: ['sweater', 'turtleneck', 'cable knit', 'winter'],
      images: [{ url: IMG.winterSweater }, { url: IMG.winterHoodie }],
      variants: { sizes: APPAREL_SIZES, colors: ['Ivory', 'Oatmeal', 'Wine'] },
      specifications: [
        { title: 'Fabric', value: 'Acrylic Wool Blend' },
        { title: 'Knit', value: 'Chunky Cable' },
        { title: 'Neck', value: 'Fold-Over Turtleneck' },
      ],
    },
    {
      name: 'Thermal Base Layer Top and Bottom Set',
      description:
        'A brushed-inside thermal set that traps warmth without adding bulk under clothes. Flatlock seams sit flat against skin so nothing rubs.',
      shortDescription: 'Brushed thermal base layer set with flatlock seams.',
      price: 1999,
      discountPrice: 1249,
      categorySlug: 'winter-wear',
      subcategory: 'Thermals',
      brand: 'Northbound',
      stock: 66,
      sku: 'WIN-THRM-36',
      rating: 4.5,
      numberOfReviews: 73,
      tags: ['thermal', 'base layer', 'winter', 'set'],
      images: [{ url: IMG.winterSweater }, { url: IMG.active2 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Black', 'Charcoal', 'Off White'] },
      specifications: [
        { title: 'Fabric', value: 'Polyester Spandex, Brushed Inside' },
        { title: 'Includes', value: 'Top + Bottom' },
        { title: 'Seams', value: 'Flatlock' },
      ],
    },

    // ---------------- ACTIVEWEAR (6 PRODUCTS) ----------------
    {
      name: 'Dry-Fit Training T-Shirt',
      description:
        'An engineered mesh tee that wicks sweat to the surface and dries fast. Raglan sleeves keep the shoulder free through overhead lifts.',
      shortDescription: 'Moisture-wicking mesh training tee with raglan sleeves.',
      price: 1499,
      discountPrice: 949,
      categorySlug: 'activewear',
      subcategory: 'Training Tees',
      brand: 'Kinetic',
      stock: 95,
      sku: 'ACT-TEE-37',
      rating: 4.6,
      numberOfReviews: 102,
      featured: true,
      bestseller: true,
      tags: ['activewear', 'tshirt', 'gym', 'dry fit'],
      images: [{ url: IMG.active1 }, { url: IMG.active4 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Black', 'Steel Grey', 'Neon Lime', 'Navy'] },
      specifications: [
        { title: 'Fabric', value: 'Polyester Engineered Mesh' },
        { title: 'Technology', value: 'Moisture-Wicking Dry-Fit' },
        { title: 'Sleeve', value: 'Raglan' },
      ],
    },
    {
      name: 'Tapered Training Joggers with Zip Pockets',
      description:
        'Four-way stretch joggers with zip side pockets that keep a phone secure mid-run. A tapered leg and elastic cuff stay out of the way.',
      shortDescription: 'Four-way stretch tapered joggers with zip pockets.',
      price: 2299,
      discountPrice: 1499,
      categorySlug: 'activewear',
      subcategory: 'Joggers',
      brand: 'Kinetic',
      stock: 68,
      sku: 'ACT-JOG-38',
      rating: 4.7,
      numberOfReviews: 84,
      featured: true,
      trending: true,
      tags: ['activewear', 'joggers', 'gym', 'running'],
      images: [{ url: IMG.active3 }, { url: IMG.active1 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Black', 'Charcoal', 'Olive'] },
      specifications: [
        { title: 'Fabric', value: 'Nylon Spandex, 4-Way Stretch' },
        { title: 'Pockets', value: '2 Zip Side Pockets' },
        { title: 'Leg', value: 'Tapered with Elastic Cuff' },
      ],
    },
    {
      name: 'High Waist Squat-Proof Gym Leggings',
      description:
        'Tested opaque through a full squat. A wide high-rise waistband stays put through burpees, with a hidden key pocket at the back.',
      shortDescription: 'Opaque high-waist gym leggings with hidden key pocket.',
      price: 2499,
      discountPrice: 1649,
      categorySlug: 'activewear',
      subcategory: 'Leggings',
      brand: 'Kinetic',
      stock: 74,
      sku: 'ACT-LEGG-39',
      rating: 4.8,
      numberOfReviews: 137,
      featured: true,
      bestseller: true,
      tags: ['activewear', 'leggings', 'gym', 'women'],
      images: [{ url: IMG.active2 }, { url: IMG.active4 }],
      variants: { sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: ['Black', 'Deep Plum', 'Slate Blue'] },
      specifications: [
        { title: 'Fabric', value: 'Nylon Spandex, Squat-Proof Knit' },
        { title: 'Rise', value: 'High Rise' },
        { title: 'Pocket', value: 'Hidden Waistband Key Pocket' },
      ],
    },
    {
      name: 'Lightweight Running Shorts with Liner',
      description:
        'Ripstop shorts with a built-in brief liner and a 5-inch inseam. Laser-cut vents at the back panel dump heat on long runs.',
      shortDescription: 'Ripstop running shorts with built-in liner and vents.',
      price: 1699,
      discountPrice: 1099,
      categorySlug: 'activewear',
      subcategory: 'Training Tees',
      brand: 'Kinetic',
      stock: 58,
      sku: 'ACT-SHRT-40',
      rating: 4.5,
      numberOfReviews: 47,
      tags: ['activewear', 'shorts', 'running'],
      images: [{ url: IMG.active4 }, { url: IMG.active3 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Black', 'Grey', 'Cobalt'] },
      specifications: [
        { title: 'Fabric', value: 'Ripstop Polyester' },
        { title: 'Inseam', value: '5 inch' },
        { title: 'Liner', value: 'Built-In Brief' },
      ],
    },
    {
      name: 'Two-Piece Tracksuit Jacket and Pants Set',
      description:
        'A matched track set in a soft poly-knit with contrast side taping. The jacket has a stand collar and both pieces carry zip pockets.',
      shortDescription: 'Poly-knit tracksuit set with contrast side taping.',
      price: 3999,
      discountPrice: 2599,
      categorySlug: 'activewear',
      subcategory: 'Track Sets',
      brand: 'Street Theory',
      stock: 34,
      sku: 'ACT-TRAC-41',
      rating: 4.6,
      numberOfReviews: 38,
      newArrival: true,
      tags: ['activewear', 'tracksuit', 'set', 'sports'],
      images: [{ url: IMG.active3 }, { url: IMG.active2 }],
      variants: { sizes: APPAREL_SIZES, colors: ['Black/White', 'Navy/Red', 'Grey/Black'] },
      specifications: [
        { title: 'Fabric', value: 'Polyester Interlock Knit' },
        { title: 'Includes', value: 'Jacket + Track Pants' },
        { title: 'Collar', value: 'Stand Collar' },
      ],
    },
    {
      name: 'Seamless Ribbed Yoga Sports Bra',
      description:
        'A seamless ribbed bra knitted in one piece so there are no seams to chafe. Medium support with removable pads and a racer back.',
      shortDescription: 'Seamless ribbed medium-support sports bra with removable pads.',
      price: 1599,
      discountPrice: 1049,
      categorySlug: 'activewear',
      subcategory: 'Leggings',
      brand: 'Form Studio',
      stock: 62,
      sku: 'ACT-BRA-42',
      rating: 4.7,
      numberOfReviews: 91,
      trending: true,
      tags: ['activewear', 'sports bra', 'yoga', 'women'],
      images: [{ url: IMG.active2 }, { url: IMG.active1 }],
      variants: { sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: ['Black', 'Sage', 'Dusty Rose'] },
      specifications: [
        { title: 'Fabric', value: 'Seamless Nylon Rib Knit' },
        { title: 'Support', value: 'Medium Impact' },
        { title: 'Pads', value: 'Removable' },
      ],
    },
  ];
};

const bannersData = [
  {
    title: 'The New Season Wardrobe Is Here',
    subtitle: 'Tailored shirts, fluid dresses and everyday denim — up to 40% OFF across the new collection.',
    image: { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1600&q=80', public_id: '' },
    link: '/shop',
    category: "Women's Clothing",
    position: 1,
    active: true,
  },
  {
    title: 'Festive Ethnic Wear Edit',
    subtitle: 'Handloom kurtas, Banarasi sarees and bridal lehengas crafted by Indian artisans.',
    image: { url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1600&q=80', public_id: '' },
    link: '/category/ethnic-wear',
    category: 'Ethnic Wear',
    position: 2,
    active: true,
  },
  {
    title: 'Winter Layers Worth Keeping',
    subtitle: 'Down puffers, merino knits and heavyweight fleece built for the cold months ahead.',
    image: { url: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?w=1600&q=80', public_id: '' },
    link: '/category/winter-wear',
    category: 'Winter Wear',
    position: 3,
    active: true,
  },
];

const couponsData = [
  {
    code: 'BAZARO20',
    discountType: 'percentage',
    discountValue: 20,
    minimumPurchase: 999,
    maximumDiscount: 500,
    expiryDate: new Date('2027-12-31'),
    usageLimit: 500,
    isActive: true,
  },
  {
    code: 'WELCOME100',
    discountType: 'fixed',
    discountValue: 100,
    minimumPurchase: 499,
    expiryDate: new Date('2027-12-31'),
    usageLimit: 1000,
    isActive: true,
  },
  {
    code: 'ETHNIC15',
    discountType: 'percentage',
    discountValue: 15,
    minimumPurchase: 2499,
    maximumDiscount: 1500,
    expiryDate: new Date('2027-12-31'),
    usageLimit: 300,
    isActive: true,
  },
];

module.exports = {
  categoriesData,
  generateProducts,
  bannersData,
  couponsData,
};
